sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wx2a8556c76e885049
    secret: 1dce82cea2eb068665c27c0c52b65aa7

  baidu-map:
    ak: WeNAD3jWKDOd12kICy0rQzjODsiiQa4k
    address: "江苏省南京市雨花台春江佳园"